name: Docker Build

on:
  push:
    branches:
      - master ## ветка(и), для которой ниже создается job при push'e


jobs:
  build:
    runs-on: ubuntu-latest ## используется ubuntu, так как там предустановлен docker

    steps:
      - name: Checkout Repository ## доступ к репозиторию
        uses: actions/checkout@v2

      - name: Docker loggin in ##вход в учетную запись dockerhub, куда будет зугружен собранный образ
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} ##логин от аккаунта 
          password: ${{ secrets.DOCKER_PASSWORD }} ##пароль от аккаунта
    
      - name: Docker loggin in ##вход в учетную запись dockerhub, куда будет зугружен собранный образ на dockerhub
        uses: docker/build-push-action@v5
        with:
          context: "./" ##Путь к папке с проектом для сборки
          push: true
          tags: philippkorkunov/test:latest
